version: '3.8'

services:

  backend_shatle:
    build:
      context: ./shatl
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    
  backend_notification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    ports:
      - "8000:8001"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
